config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :logins, only: %i[new create]
  resources :registrations, only: %i[new create]
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true
    validates :email, presence: true
    validates :password, presence: true 
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to posts_path if user
    @user = User.new
  end

  def create
    @user = User.find_by(login_params)

    if @user 
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      flash[:alert] = "Email or password is wrong"
      render :new, status: :unprocessable_entity
    end
  end

  private 

    def login_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :is_authorized?, only: [:show, :edit, :update]
    before_action :redirect_unauthorized, only: [:edit, :update]
    before_action :is_authenticated?, only: [:index, :new]
    before_action :set_user_id, only: [:new, :create, :edit, :update]
    def index 
        @posts = Post.all
    end

    def show
    end

    def new 
        @post = Post.new
        redirect_to posts_path unless @authenticated
    end

    def create 
        @post = Post.new(post_params)
      
        if @post.save
            redirect_to posts_path
        else 
            flash.now[:notice] = "Could not save post."
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        if @post.update(post_params)
            redirect_to @post
        else
            flash.now[:notice] = "Could not update Post."
            render :edit, status: :unprocessable_entity
        end
    end

    private 
        def post_params
            params.require(:post).permit(:title, :body, :user_id)
        end

        def current_user
            User.find_by(id: session[:user_id])
        end

        def is_authorized? 
            @post = Post.find(params[:id])
            @authorized = @post.user == current_user             
        end

        def is_authenticated?
            @authenticated = current_user != nil
        end

        def redirect_unauthorized
            redirect_to posts_path unless @authorized
        end

        def set_user_id
            @user_id = session[:user_id]
        end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

    def new
        user = User.find_by(id: session[:user_id])
        redirect_to posts_path if user
        @user = User.new
    end

    def create
        @user = User.create(user_params)

        if @user.save 
            redirect_to new_login_path
        else
            flash[:alert] = "Could not save user."
            render :new, status: :unprocessable_entity
        end 
    end

    private 
        def user_params()
            params.require(:user).permit(:username, :email, :password)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div><%= notice %></div>
    <div><%= alert %></div>
    <%= yield %>
  </body>
</html>

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/new.html.erb
<h1>Log in</h1>

<%= form_with model: @user, url: logins_path do |form| %>
    <div>
        <%= form.label :email %>
        <%= form.email_field :email %>
    </div>
    <div>
        <%= form.label :password %>
        <%= form.password_field :password %>
    </div>
    
    <div>
        <%= form.submit "Log in" %>
    </div>

<% end %>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% post.errors.full_messages_for(:title).each do |message| %>
          <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
      <% post.errors.full_messages_for(:body).each do |message| %>
          <div><%= message %></div>
      <% end %>
    </div>
    <div>
        <%= form.number_field :user_id, id: :post_user_id, value: @user_id,
            type: :hidden %>
    </div>
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul>
  <% @posts.each do |post| %>
      <div>
        <li>
         <%= link_to post.title, post %> by <%= post.user.username %>
        </li>
      </div>
  <% end %>
</ul>

<% if @authenticated %>
  <%= link_to "New Post", new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>

<p><%= @post.user.username %></p>

<% if @authorized %>
    <ul>
    <li><%= link_to "Edit", edit_post_path(@post) %></li>
    </ul>
<% end %>